---

# Skip settings
skip:
  paths:  # Paths and files
    - .git/
    - LICENSE.md
  types:  # File types (extensions)
    - bin
    - dat

# Snippet parser settings
snippet:
  lines_min: 3  # snippets not less than X lines

similarity:
  identical: true  # set to true to include actually identical snippets
  ratio_fail: 95
  topk: 3  # how many top similars to display if check not failed
